on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: 1.2.5
          terraform_wrapper: false
      - run: |
          terraform init
          terraform validate
        working-directory: examples/
