on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: 1.2.5
          terraform_wrapper: false
      - run: |
          terraform init
          terraform validate
        working-directory: examples/
